import { Text, View, Pressable, ScrollView, Alert } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useFamily } from "@/lib/family-store";
import { useI18n } from "@/lib/i18n";
import { useState } from "react";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import * as MailComposer from "expo-mail-composer";
import * as DocumentPicker from "expo-document-picker";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { FamilyData } from "@/lib/types";

const BACKUP_DATE_KEY = "@waris_last_backup";

export default function BackupRestoreScreen() {
  const router = useRouter();
  const colors = useColors();
  const { data } = useFamily();
  const { t } = useI18n();
  const [exporting, setExporting] = useState(false);
  const [importing, setImporting] = useState(false);
  const [lastBackup, setLastBackup] = useState<string | null>(null);

  // Load last backup date
  AsyncStorage.getItem(BACKUP_DATE_KEY).then((d) => {
    if (d && !lastBackup) setLastBackup(d);
  });

  const createBackupFile = async (): Promise<string | null> => {
    try {
      const json = JSON.stringify(data, null, 2);
      const fileName = `waris-backup-${new Date().toISOString().split("T")[0]}.json`;
      const filePath = `${FileSystem.documentDirectory}${fileName}`;
      await FileSystem.writeAsStringAsync(filePath, json, { encoding: FileSystem.EncodingType.UTF8 });
      const now = new Date().toLocaleString("en-MY");
      await AsyncStorage.setItem(BACKUP_DATE_KEY, now);
      setLastBackup(now);
      return filePath;
    } catch (e) {
      Alert.alert("Error", "Failed to create backup file.");
      return null;
    }
  };

  const handleCreateBackup = async () => {
    if (data.persons.length === 0) {
      Alert.alert("No Data", "Please add family members before creating a backup.");
      return;
    }
    setExporting(true);
    try {
      const filePath = await createBackupFile();
      if (filePath) {
        const canShare = await Sharing.isAvailableAsync();
        if (canShare) {
          await Sharing.shareAsync(filePath, {
            mimeType: "application/json",
            dialogTitle: "Save Waris Backup",
          });
        } else {
          Alert.alert("Backup Created", "Backup file saved to app storage.");
        }
      }
    } catch (e) {
      Alert.alert("Error", "Failed to create backup.");
    } finally {
      setExporting(false);
    }
  };

  const handleShareViaEmail = async () => {
    if (data.persons.length === 0) {
      Alert.alert("No Data", "Please add family members before sharing.");
      return;
    }
    setExporting(true);
    try {
      const filePath = await createBackupFile();
      if (filePath) {
        const isAvailable = await MailComposer.isAvailableAsync();
        if (isAvailable) {
          await MailComposer.composeAsync({
            subject: `Waris Genealogy Backup - ${data.familyName}`,
            body: `Attached is the family tree backup for "${data.familyName}" containing ${data.persons.length} members.\n\nGenerated by Waris Genealogy App.`,
            attachments: [filePath],
          });
        } else {
          // Fallback to sharing
          const canShare = await Sharing.isAvailableAsync();
          if (canShare) {
            await Sharing.shareAsync(filePath, {
              mimeType: "application/json",
              dialogTitle: "Share Waris Backup via Email",
            });
          } else {
            Alert.alert("Email Not Available", "No email client is configured on this device. The backup has been saved locally.");
          }
        }
      }
    } catch (e) {
      Alert.alert("Error", "Failed to share via email.");
    } finally {
      setExporting(false);
    }
  };

  const handleShareToDrive = async () => {
    if (data.persons.length === 0) {
      Alert.alert("No Data", "Please add family members before sharing.");
      return;
    }
    setExporting(true);
    try {
      const filePath = await createBackupFile();
      if (filePath) {
        const canShare = await Sharing.isAvailableAsync();
        if (canShare) {
          await Sharing.shareAsync(filePath, {
            mimeType: "application/json",
            dialogTitle: "Save to Google Drive",
            UTI: "public.json",
          });
        } else {
          Alert.alert("Sharing Not Available", "Sharing is not available on this device.");
        }
      }
    } catch (e) {
      Alert.alert("Error", "Failed to share to Google Drive.");
    } finally {
      setExporting(false);
    }
  };

  const handleRestore = async () => {
    setImporting(true);
    try {
      const result = await DocumentPicker.getDocumentAsync({
        type: "application/json",
        copyToCacheDirectory: true,
      });

      if (!result.canceled && result.assets && result.assets.length > 0) {
        const fileUri = result.assets[0].uri;
        const content = await FileSystem.readAsStringAsync(fileUri, { encoding: FileSystem.EncodingType.UTF8 });
        const parsed = JSON.parse(content) as FamilyData;

        // Validate structure
        if (!parsed.persons || !Array.isArray(parsed.persons)) {
          Alert.alert("Invalid File", "The selected file does not contain valid family data.");
          return;
        }

        Alert.alert(
          "Restore Data",
          `This will replace all current data with the backup containing ${parsed.persons.length} members. This action cannot be undone.`,
          [
            { text: "Cancel", style: "cancel" },
            {
              text: "Restore",
              style: "destructive",
              onPress: async () => {
                try {
                  await AsyncStorage.setItem("@waris_family_data", JSON.stringify(parsed));
                  Alert.alert("Restored", `Successfully restored ${parsed.persons.length} members. Please restart the app to see changes.`);
                } catch (e) {
                  Alert.alert("Error", "Failed to restore data.");
                }
              },
            },
          ]
        );
      }
    } catch (e) {
      Alert.alert("Error", "Failed to read backup file.");
    } finally {
      setImporting(false);
    }
  };

  return (
    <ScreenContainer className="pt-2">
      {/* Header */}
      <View className="flex-row items-center px-5 mb-4 gap-3">
        <Pressable onPress={() => router.back()} style={({ pressed }) => [{ opacity: pressed ? 0.7 : 1 }]}>
          <View className="flex-row items-center gap-1">
            <IconSymbol name="chevron.left" size={20} color={colors.primary} />
            <Text className="text-sm" style={{ color: colors.primary }}>{t("back")}</Text>
          </View>
        </Pressable>
        <Text className="text-xl font-bold text-foreground flex-1">{t("backupTitle")}</Text>
      </View>

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingHorizontal: 20, paddingBottom: 40 }}>
        {/* Status Card */}
        <View className="bg-surface rounded-2xl p-4 border border-border mb-6">
          <View className="flex-row items-center gap-3 mb-3">
            <View className="w-12 h-12 rounded-xl bg-primary/10 items-center justify-center">
              <IconSymbol name="folder.fill" size={24} color={colors.primary} />
            </View>
            <View className="flex-1">
              <Text className="text-base font-semibold text-foreground">{data.familyName}</Text>
              <Text className="text-xs text-muted">
                {data.persons.length} members · {data.marriages.length} marriages
              </Text>
            </View>
          </View>
          <View className="flex-row items-center gap-2">
            <IconSymbol name="clock.fill" size={14} color={colors.muted} />
            <Text className="text-xs text-muted">
              {t("lastBackup")}: {lastBackup || t("never")}
            </Text>
          </View>
        </View>

        {/* Backup Section */}
        <Text className="text-xs font-semibold text-muted uppercase tracking-wider mb-3">BACKUP</Text>
        <View className="gap-3 mb-6">
          {/* Create Backup */}
          <Pressable
            onPress={handleCreateBackup}
            style={({ pressed }) => [{ opacity: exporting ? 0.5 : pressed ? 0.7 : 1 }]}
            disabled={exporting}
          >
            <View className="flex-row items-center bg-surface rounded-2xl p-4 border border-border gap-4">
              <View className="w-11 h-11 rounded-xl items-center justify-center" style={{ backgroundColor: colors.success + "18" }}>
                <IconSymbol name="arrow.down.doc.fill" size={22} color={colors.success} />
              </View>
              <View className="flex-1">
                <Text className="text-sm font-semibold text-foreground">{t("createBackup")}</Text>
                <Text className="text-xs text-muted mt-0.5">{exporting ? "Creating..." : t("createBackupDesc")}</Text>
              </View>
              <IconSymbol name="chevron.right" size={16} color={colors.muted} />
            </View>
          </Pressable>

          {/* Share via Gmail */}
          <Pressable
            onPress={handleShareViaEmail}
            style={({ pressed }) => [{ opacity: exporting ? 0.5 : pressed ? 0.7 : 1 }]}
            disabled={exporting}
          >
            <View className="flex-row items-center bg-surface rounded-2xl p-4 border border-border gap-4">
              <View className="w-11 h-11 rounded-xl items-center justify-center" style={{ backgroundColor: "#EA4335" + "18" }}>
                <IconSymbol name="envelope.fill" size={22} color="#EA4335" />
              </View>
              <View className="flex-1">
                <Text className="text-sm font-semibold text-foreground">{t("shareViaGmail")}</Text>
                <Text className="text-xs text-muted mt-0.5">{t("shareViaGmailDesc")}</Text>
              </View>
              <IconSymbol name="chevron.right" size={16} color={colors.muted} />
            </View>
          </Pressable>

          {/* Share to Google Drive */}
          <Pressable
            onPress={handleShareToDrive}
            style={({ pressed }) => [{ opacity: exporting ? 0.5 : pressed ? 0.7 : 1 }]}
            disabled={exporting}
          >
            <View className="flex-row items-center bg-surface rounded-2xl p-4 border border-border gap-4">
              <View className="w-11 h-11 rounded-xl items-center justify-center" style={{ backgroundColor: "#4285F4" + "18" }}>
                <IconSymbol name="arrow.up.doc.fill" size={22} color="#4285F4" />
              </View>
              <View className="flex-1">
                <Text className="text-sm font-semibold text-foreground">{t("shareViaDrive")}</Text>
                <Text className="text-xs text-muted mt-0.5">{t("shareViaDriveDesc")}</Text>
              </View>
              <IconSymbol name="chevron.right" size={16} color={colors.muted} />
            </View>
          </Pressable>
        </View>

        {/* Restore Section */}
        <Text className="text-xs font-semibold text-muted uppercase tracking-wider mb-3">RESTORE</Text>
        <Pressable
          onPress={handleRestore}
          style={({ pressed }) => [{ opacity: importing ? 0.5 : pressed ? 0.7 : 1 }]}
          disabled={importing}
        >
          <View className="flex-row items-center bg-surface rounded-2xl p-4 border border-border gap-4">
            <View className="w-11 h-11 rounded-xl items-center justify-center" style={{ backgroundColor: colors.warning + "18" }}>
              <IconSymbol name="arrow.clockwise" size={22} color={colors.warning} />
            </View>
            <View className="flex-1">
              <Text className="text-sm font-semibold text-foreground">{t("restoreData")}</Text>
              <Text className="text-xs text-muted mt-0.5">{importing ? "Importing..." : t("restoreDataDesc")}</Text>
            </View>
            <IconSymbol name="chevron.right" size={16} color={colors.muted} />
          </View>
        </Pressable>

        {/* Warning */}
        <View className="mt-6 bg-warning/8 rounded-2xl p-4 border" style={{ borderColor: colors.warning + "30" }}>
          <View className="flex-row items-start gap-3">
            <IconSymbol name="exclamationmark.triangle.fill" size={18} color={colors.warning} />
            <View className="flex-1">
              <Text className="text-sm font-medium text-foreground mb-1">Important</Text>
              <Text className="text-xs text-muted leading-relaxed">
                Restoring from a backup will replace all current data. Make sure to create a backup of your current data first if needed.
              </Text>
            </View>
          </View>
        </View>
      </ScrollView>
    </ScreenContainer>
  );
}
