import * as Print from "expo-print";
import { Platform } from "react-native";
import { FamilyData, Person, getDisplayName } from "./types";

function generateFamilyTreeHTML(data: FamilyData): string {
  const { persons, marriages, parentChildren, familyName } = data;
  const totalMembers = persons.length;
  const livingMembers = persons.filter((p) => p.isAlive).length;
  const deceasedMembers = totalMembers - livingMembers;

  const getChildren = (personId: string): Person[] => {
    const childIds = parentChildren.filter((pc) => pc.parentId === personId).map((pc) => pc.childId);
    return persons.filter((p) => childIds.includes(p.id));
  };

  const getSpouses = (personId: string): Person[] => {
    const spouseIds = marriages
      .filter((m) => m.husbandId === personId || m.wifeId === personId)
      .map((m) => (m.husbandId === personId ? m.wifeId : m.husbandId));
    return persons.filter((p) => spouseIds.includes(p.id));
  };

  const getParents = (personId: string): Person[] => {
    const parentIds = parentChildren.filter((pc) => pc.childId === personId).map((pc) => pc.parentId);
    return persons.filter((p) => parentIds.includes(p.id));
  };

  const memberRows = persons
    .map((p) => {
      const parents = getParents(p.id).map((pp) => getDisplayName(pp)).join(", ");
      const spouses = getSpouses(p.id).map((sp) => getDisplayName(sp)).join(", ");
      const children = getChildren(p.id).map((ch) => getDisplayName(ch)).join(", ");
      return `
        <tr>
          <td>${getDisplayName(p)}</td>
          <td>${p.gender === "male" ? "M" : "F"}</td>
          <td>${p.birthDate || "-"}</td>
          <td>${p.isAlive ? "Living" : "Deceased"}</td>
          <td>${p.race || "-"}</td>
          <td>${p.religion || "-"}</td>
          <td style="font-size:9px">${parents || "-"}</td>
          <td style="font-size:9px">${spouses || "-"}</td>
          <td style="font-size:9px">${children || "-"}</td>
        </tr>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    @page { margin: 15mm; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a1a; font-size: 11px; line-height: 1.4; }
    .header { text-align: center; margin-bottom: 20px; border-bottom: 3px solid #1B5E20; padding-bottom: 15px; }
    .header h1 { color: #1B5E20; font-size: 24px; margin: 0 0 5px 0; }
    .header p { color: #666; font-size: 12px; margin: 2px 0; }
    .stats { display: flex; justify-content: center; gap: 30px; margin: 15px 0; }
    .stat { text-align: center; }
    .stat .num { font-size: 22px; font-weight: bold; color: #1B5E20; }
    .stat .label { font-size: 10px; color: #888; text-transform: uppercase; }
    table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    th { background: #1B5E20; color: white; padding: 8px 6px; text-align: left; font-size: 10px; text-transform: uppercase; }
    td { padding: 6px; border-bottom: 1px solid #e0e0e0; font-size: 10px; }
    tr:nth-child(even) { background: #f9f9f9; }
    .footer { text-align: center; margin-top: 20px; font-size: 9px; color: #999; border-top: 1px solid #e0e0e0; padding-top: 10px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${familyName}</h1>
    <p>Family Tree Report</p>
    <p>Generated on ${new Date().toLocaleDateString("en-MY", { year: "numeric", month: "long", day: "numeric" })}</p>
  </div>

  <div class="stats">
    <div class="stat"><div class="num">${totalMembers}</div><div class="label">Total Members</div></div>
    <div class="stat"><div class="num">${livingMembers}</div><div class="label">Living</div></div>
    <div class="stat"><div class="num">${deceasedMembers}</div><div class="label">Deceased</div></div>
    <div class="stat"><div class="num">${marriages.length}</div><div class="label">Marriages</div></div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Gender</th>
        <th>Birth Date</th>
        <th>Status</th>
        <th>Ethnicity</th>
        <th>Religion</th>
        <th>Parents</th>
        <th>Spouse(s)</th>
        <th>Children</th>
      </tr>
    </thead>
    <tbody>
      ${memberRows}
    </tbody>
  </table>

  <div class="footer">
    <p>Generated by Waris - Genealogy &amp; Family Tree App</p>
    <p>This document is for personal family records only.</p>
  </div>
</body>
</html>`;
}

interface FaraidResult {
  heir: string;
  share: string;
  amount: number;
}

function generateFaraidHTML(
  familyName: string,
  deceasedName: string,
  totalEstate: number,
  heirs: FaraidResult[]
): string {
  const heirRows = heirs
    .map(
      (h) => `
      <tr>
        <td>${h.heir}</td>
        <td>${h.share}</td>
        <td style="text-align:right">RM ${h.amount.toLocaleString("en-MY", { minimumFractionDigits: 2 })}</td>
      </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    @page { margin: 20mm; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a1a; font-size: 12px; line-height: 1.5; }
    .header { text-align: center; margin-bottom: 25px; border-bottom: 3px solid #1B5E20; padding-bottom: 15px; }
    .header h1 { color: #1B5E20; font-size: 22px; margin: 0 0 5px 0; }
    .header h2 { color: #333; font-size: 16px; margin: 0 0 5px 0; font-weight: normal; }
    .header p { color: #666; font-size: 11px; margin: 2px 0; }
    .info-box { background: #f5f5f5; border: 1px solid #e0e0e0; border-radius: 8px; padding: 15px; margin: 15px 0; }
    .info-row { display: flex; justify-content: space-between; margin: 5px 0; }
    .info-label { color: #666; font-size: 11px; }
    .info-value { font-weight: bold; font-size: 13px; }
    .total { font-size: 18px; color: #1B5E20; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { background: #1B5E20; color: white; padding: 10px 8px; text-align: left; font-size: 11px; text-transform: uppercase; }
    td { padding: 10px 8px; border-bottom: 1px solid #e0e0e0; }
    tr:nth-child(even) { background: #f9f9f9; }
    .note { background: #FFF8E1; border: 1px solid #FFE082; border-radius: 8px; padding: 12px; margin-top: 20px; font-size: 10px; color: #795548; }
    .footer { text-align: center; margin-top: 25px; font-size: 9px; color: #999; border-top: 1px solid #e0e0e0; padding-top: 10px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Faraid Distribution Report</h1>
    <h2>${familyName}</h2>
    <p>Generated on ${new Date().toLocaleDateString("en-MY", { year: "numeric", month: "long", day: "numeric" })}</p>
  </div>

  <div class="info-box">
    <div class="info-row">
      <span class="info-label">Deceased (Si Mati):</span>
      <span class="info-value">${deceasedName}</span>
    </div>
    <div class="info-row">
      <span class="info-label">Total Estate (Jumlah Harta):</span>
      <span class="info-value total">RM ${totalEstate.toLocaleString("en-MY", { minimumFractionDigits: 2 })}</span>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Heir (Waris)</th>
        <th>Share (Bahagian)</th>
        <th style="text-align:right">Amount (Jumlah)</th>
      </tr>
    </thead>
    <tbody>
      ${heirRows}
    </tbody>
  </table>

  <div class="note">
    <strong>Disclaimer / Penafian:</strong> This calculation is for reference purposes only (Pengiraan ini adalah untuk rujukan sahaja). 
    Please consult a qualified Islamic scholar or Syariah lawyer for official Faraid distribution. 
    Sila rujuk ulama atau peguam Syariah yang bertauliah untuk pengagihan Faraid rasmi.
  </div>

  <div class="footer">
    <p>Generated by Waris - Genealogy &amp; Family Tree App</p>
    <p>This document is for personal family records only.</p>
  </div>
</body>
</html>`;
}

export async function exportFamilyTreePDF(data: FamilyData) {
  const html = generateFamilyTreeHTML(data);
  // Use printAsync which opens system print dialog (includes Save as PDF / Share options)
  await Print.printAsync({ html });
}

export async function exportFaraidPDF(
  familyName: string,
  deceasedName: string,
  totalEstate: number,
  heirs: FaraidResult[]
) {
  const html = generateFaraidHTML(familyName, deceasedName, totalEstate, heirs);
  // Use printAsync which opens system print dialog (includes Save as PDF / Share options)
  await Print.printAsync({ html });
}

export async function printFamilyTree(data: FamilyData) {
  const html = generateFamilyTreeHTML(data);
  await Print.printAsync({ html });
}
